/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tubes;

import java.awt.HeadlessException;
import java.beans.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static sun.jvm.hotspot.HelloWorld.e;

/**
 *
 * @author ASUS
 */
public class Test extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Test() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jKelamin = new javax.swing.ButtonGroup();
        lapButtonGroup = new javax.swing.ButtonGroup();
        side = new javax.swing.JPanel();
        logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new javax.swing.JLabel();
        btnKtpInput = new javax.swing.JLabel();
        btnInput = new javax.swing.JLabel();
        btnLaporanInput = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCekKtp = new javax.swing.JLabel();
        btnCekLaporan = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        conten = new javax.swing.JPanel();
        defaultPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        homePanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        laporanInput = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        nikLapField = new javax.swing.JTextField();
        namaLapField = new javax.swing.JTextField();
        rtLapField = new javax.swing.JTextField();
        lakiLapButton = new javax.swing.JRadioButton();
        perempuanLapButton = new javax.swing.JRadioButton();
        noTelpLapField = new javax.swing.JTextField();
        tglLapField = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        isiLapTextArea = new javax.swing.JTextArea();
        kirimLapButton = new javax.swing.JButton();
        pelecehanRadioButton = new javax.swing.JRadioButton();
        jalanRusakRadioButton = new javax.swing.JRadioButton();
        lainnyaRadioButton = new javax.swing.JRadioButton();
        kejahatanRadioButton = new javax.swing.JRadioButton();
        lainnyaLapField = new javax.swing.JTextField();
        rwLapField = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        ktpInput = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        nikField = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        namaField = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        alamatTextArea = new javax.swing.JTextArea();
        jLabel25 = new javax.swing.JLabel();
        rtField = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        desatField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        kecField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        kabField = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        wargaField = new javax.swing.JTextField();
        ttlField = new javax.swing.JTextField();
        pekerjaanField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        statustField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        lakiButton = new javax.swing.JRadioButton();
        perempuanButton = new javax.swing.JRadioButton();
        jLabel32 = new javax.swing.JLabel();
        noTelpField = new javax.swing.JTextField();
        kirimButton = new javax.swing.JButton();
        ktpCek = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        laporanCek = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIMPEDA");

        side.setBackground(new java.awt.Color(120, 104, 230));

        logo.setBackground(new java.awt.Color(184, 181, 255));

        jLabel1.setBackground(new java.awt.Color(184, 181, 255));
        jLabel1.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LORD ACADEMY");

        javax.swing.GroupLayout logoLayout = new javax.swing.GroupLayout(logo);
        logo.setLayout(logoLayout);
        logoLayout.setHorizontalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        logoLayout.setVerticalGroup(
            logoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        btnHome.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setText("HOME");
        btnHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHomeMouseClicked(evt);
            }
        });

        btnKtpInput.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        btnKtpInput.setForeground(new java.awt.Color(255, 255, 255));
        btnKtpInput.setText("KTP");
        btnKtpInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKtpInputMouseClicked(evt);
            }
        });

        btnInput.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        btnInput.setForeground(new java.awt.Color(255, 255, 255));
        btnInput.setText("INPUT DATA");

        btnLaporanInput.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        btnLaporanInput.setForeground(new java.awt.Color(255, 255, 255));
        btnLaporanInput.setText("LAPORAN");
        btnLaporanInput.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLaporanInputMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("LOG OUT");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        btnCekKtp.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        btnCekKtp.setForeground(new java.awt.Color(255, 255, 255));
        btnCekKtp.setText("KTP");
        btnCekKtp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCekKtpMouseClicked(evt);
            }
        });

        btnCekLaporan.setFont(new java.awt.Font("Poppins SemiBold", 0, 12)); // NOI18N
        btnCekLaporan.setForeground(new java.awt.Color(255, 255, 255));
        btnCekLaporan.setText("LAPORAN");
        btnCekLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCekLaporanMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CEK STATUS");

        javax.swing.GroupLayout sideLayout = new javax.swing.GroupLayout(side);
        side.setLayout(sideLayout);
        sideLayout.setHorizontalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnLaporanInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(btnKtpInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(btnCekKtp, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCekLaporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addContainerGap())
        );
        sideLayout.setVerticalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnKtpInput)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLaporanInput)
                .addGap(17, 17, 17)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCekKtp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCekLaporan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(22, 22, 22))
        );

        conten.setBackground(new java.awt.Color(255, 255, 255));
        conten.setLayout(new java.awt.CardLayout());

        defaultPanel.setBackground(new java.awt.Color(237, 238, 247));

        jLabel2.setFont(new java.awt.Font("Poppins ExtraBold", 3, 24)); // NOI18N
        jLabel2.setText("SELAMAT DATANG DI SISTEM PELAYAN DESA");

        javax.swing.GroupLayout defaultPanelLayout = new javax.swing.GroupLayout(defaultPanel);
        defaultPanel.setLayout(defaultPanelLayout);
        defaultPanelLayout.setHorizontalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultPanelLayout.createSequentialGroup()
                .addGroup(defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(defaultPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel2))
                    .addGroup(defaultPanelLayout.createSequentialGroup()
                        .addGap(264, 264, 264)
                        .addComponent(jLabel5)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        defaultPanelLayout.setVerticalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, defaultPanelLayout.createSequentialGroup()
                .addContainerGap(161, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(66, 66, 66)
                .addComponent(jLabel2)
                .addGap(183, 183, 183))
        );

        conten.add(defaultPanel, "card4");

        homePanel.setBackground(new java.awt.Color(237, 238, 247));

        jLabel3.setFont(new java.awt.Font("Poppins ExtraBold", 3, 14)); // NOI18N
        jLabel3.setText("HOMEPAGES");

        javax.swing.GroupLayout homePanelLayout = new javax.swing.GroupLayout(homePanel);
        homePanel.setLayout(homePanelLayout);
        homePanelLayout.setHorizontalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addGroup(homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(homePanelLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel7)))
                .addContainerGap(596, Short.MAX_VALUE))
        );
        homePanelLayout.setVerticalGroup(
            homePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(69, 69, 69)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        conten.add(homePanel, "card3");

        laporanInput.setBackground(new java.awt.Color(237, 238, 247));

        jLabel8.setFont(new java.awt.Font("Poppins ExtraBold", 3, 14)); // NOI18N
        jLabel8.setText("INPUT DATA LAPORAN");

        jLabel14.setText("Masukan NIK : ");

        jLabel15.setText("RT : ");

        jLabel16.setText("Masukan Nama : ");

        jLabel17.setText("Jenis Kelamin :");

        jLabel18.setText("Kategori laporan :");

        jLabel19.setText("No Telpon :");

        jLabel20.setText("Tanggal Laporan :");

        jKelamin.add(lakiLapButton);
        lakiLapButton.setText("Laki - Laki");
        lakiLapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiLapButtonActionPerformed(evt);
            }
        });

        jKelamin.add(perempuanLapButton);
        perempuanLapButton.setText("Perempuan");

        tglLapField.setText("(TTTT-BB-HH)");
        tglLapField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglLapFieldActionPerformed(evt);
            }
        });

        jLabel21.setText("Isi Laporan  :");

        isiLapTextArea.setColumns(20);
        isiLapTextArea.setRows(5);
        jScrollPane1.setViewportView(isiLapTextArea);

        kirimLapButton.setText("Kirim");
        kirimLapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimLapButtonActionPerformed(evt);
            }
        });

        lapButtonGroup.add(pelecehanRadioButton);
        pelecehanRadioButton.setText("Pelecehan");
        pelecehanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pelecehanRadioButtonActionPerformed(evt);
            }
        });

        lapButtonGroup.add(jalanRusakRadioButton);
        jalanRusakRadioButton.setText("Jalan Rusak");

        lainnyaRadioButton.setText("Lainnya");
        lainnyaRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lainnyaRadioButtonActionPerformed(evt);
            }
        });

        lapButtonGroup.add(kejahatanRadioButton);
        kejahatanRadioButton.setText("Kejahatan");
        kejahatanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kejahatanRadioButtonActionPerformed(evt);
            }
        });

        lainnyaLapField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lainnyaLapFieldActionPerformed(evt);
            }
        });

        jLabel33.setText("RW : ");

        javax.swing.GroupLayout laporanInputLayout = new javax.swing.GroupLayout(laporanInput);
        laporanInput.setLayout(laporanInputLayout);
        laporanInputLayout.setHorizontalGroup(
            laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanInputLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laporanInputLayout.createSequentialGroup()
                        .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(laporanInputLayout.createSequentialGroup()
                                .addComponent(pelecehanRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(kejahatanRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(jalanRusakRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(lainnyaRadioButton)
                                .addGap(0, 215, Short.MAX_VALUE))
                            .addComponent(lainnyaLapField)
                            .addComponent(noTelpLapField)
                            .addComponent(tglLapField)))
                    .addGroup(laporanInputLayout.createSequentialGroup()
                        .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(25, 25, 25)
                        .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nikLapField)
                            .addComponent(namaLapField)
                            .addComponent(rtLapField)
                            .addGroup(laporanInputLayout.createSequentialGroup()
                                .addComponent(lakiLapButton)
                                .addGap(18, 18, 18)
                                .addComponent(perempuanLapButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(rwLapField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanInputLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kirimLapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, laporanInputLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(247, 247, 247))
        );
        laporanInputLayout.setVerticalGroup(
            laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nikLapField, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namaLapField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtLapField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rwLapField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(perempuanLapButton)
                        .addComponent(lakiLapButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noTelpLapField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kejahatanRadioButton)
                    .addComponent(pelecehanRadioButton)
                    .addComponent(jalanRusakRadioButton)
                    .addComponent(lainnyaRadioButton)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(lainnyaLapField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tglLapField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(13, 13, 13)
                .addGroup(laporanInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laporanInputLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                        .addGap(11, 11, 11))
                    .addGroup(laporanInputLayout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(kirimLapButton)
                .addGap(32, 32, 32))
        );

        conten.add(laporanInput, "card4");

        ktpInput.setBackground(new java.awt.Color(237, 238, 247));

        jLabel10.setFont(new java.awt.Font("Poppins ExtraBold", 3, 14)); // NOI18N
        jLabel10.setText("INPUT DATA KTP");

        jLabel22.setText("Masukkan NIK :");

        jLabel23.setText("Masukkan Nama :");

        jLabel24.setText("Alamat :");

        alamatTextArea.setColumns(20);
        alamatTextArea.setRows(5);
        jScrollPane2.setViewportView(alamatTextArea);

        jLabel25.setText("RT/RW :");

        jLabel26.setText("Desa : ");

        jLabel27.setText("Kecamatan :");

        jLabel28.setText("Kabupaten :");

        jLabel29.setText("Kewarganegaraan :");

        jLabel30.setText("Tempat, tanggal lahir :");

        jLabel31.setText("Pekerjaan :");

        pekerjaanField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pekerjaanFieldActionPerformed(evt);
            }
        });

        jLabel4.setText("Status :");

        statustField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statustFieldActionPerformed(evt);
            }
        });

        jLabel12.setText("Jenis Kelamin : ");

        jKelamin.add(lakiButton);
        lakiButton.setText("Laki - laki");

        jKelamin.add(perempuanButton);
        perempuanButton.setText("Perempuan");

        jLabel32.setText("No Telepon :");

        kirimButton.setText("Kirim");
        kirimButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kirimButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ktpInputLayout = new javax.swing.GroupLayout(ktpInput);
        ktpInput.setLayout(ktpInputLayout);
        ktpInputLayout.setHorizontalGroup(
            ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ktpInputLayout.createSequentialGroup()
                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ktpInputLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ktpInputLayout.createSequentialGroup()
                                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ttlField)
                                    .addComponent(pekerjaanField)))
                            .addGroup(ktpInputLayout.createSequentialGroup()
                                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(statustField)
                                    .addGroup(ktpInputLayout.createSequentialGroup()
                                        .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(perempuanButton)
                                            .addComponent(lakiButton))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(ktpInputLayout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(noTelpField))
                            .addGroup(ktpInputLayout.createSequentialGroup()
                                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(ktpInputLayout.createSequentialGroup()
                                        .addGap(5, 5, 5)
                                        .addComponent(jLabel10))
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaField)
                                    .addComponent(nikField)))
                            .addGroup(ktpInputLayout.createSequentialGroup()
                                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE)
                                    .addComponent(rtField)
                                    .addComponent(desatField)
                                    .addComponent(kecField)
                                    .addComponent(kabField)
                                    .addComponent(wargaField)))))
                    .addGroup(ktpInputLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kirimButton, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        ktpInputLayout.setVerticalGroup(
            ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ktpInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nikField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaField, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rtField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(desatField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kecField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kabField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wargaField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(ttlField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pekerjaanField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statustField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lakiButton)
                    .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(perempuanButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ktpInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noTelpField, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(kirimButton)
                .addGap(24, 24, 24))
        );

        conten.add(ktpInput, "card5");

        ktpCek.setBackground(new java.awt.Color(237, 238, 247));

        jLabel11.setFont(new java.awt.Font("Poppins ExtraBold", 3, 14)); // NOI18N
        jLabel11.setText("CEK STATUS KTP");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout ktpCekLayout = new javax.swing.GroupLayout(ktpCek);
        ktpCek.setLayout(ktpCekLayout);
        ktpCekLayout.setHorizontalGroup(
            ktpCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ktpCekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ktpCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ktpCekLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE))
                .addContainerGap())
        );
        ktpCekLayout.setVerticalGroup(
            ktpCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ktpCekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        conten.add(ktpCek, "card6");

        laporanCek.setBackground(new java.awt.Color(237, 238, 247));

        jLabel13.setFont(new java.awt.Font("Poppins ExtraBold", 3, 14)); // NOI18N
        jLabel13.setText("CEK STATUS LAPORAN");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nama", "Jenis Laporan", "Status"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        javax.swing.GroupLayout laporanCekLayout = new javax.swing.GroupLayout(laporanCek);
        laporanCek.setLayout(laporanCekLayout);
        laporanCekLayout.setHorizontalGroup(
            laporanCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanCekLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(laporanCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(laporanCekLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 719, Short.MAX_VALUE))
                .addContainerGap())
        );
        laporanCekLayout.setVerticalGroup(
            laporanCekLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(laporanCekLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        conten.add(laporanCek, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(side, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(side, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(conten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHomeMouseClicked
        // TODO add your handling code here:
        homePanel.setVisible(true);
        laporanInput.setVisible(false);
        ktpCek.setVisible(false);
        ktpInput.setVisible(false);
        laporanCek.setVisible(false);
        defaultPanel.setVisible(false);
    }//GEN-LAST:event_btnHomeMouseClicked

    private void btnKtpInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKtpInputMouseClicked
        // TODO add your handling code here:
        laporanInput.setVisible(false);
        homePanel.setVisible(false);
        ktpCek.setVisible(false);
        ktpInput.setVisible(true);
        laporanCek.setVisible(false);
        defaultPanel.setVisible(false);
    }//GEN-LAST:event_btnKtpInputMouseClicked

    private void btnLaporanInputMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLaporanInputMouseClicked
        // TODO add your handling code here:
        ktpInput.setVisible(false);
        homePanel.setVisible(false);
        laporanInput.setVisible(true);
        ktpCek.setVisible(false);
        laporanCek.setVisible(false);
        defaultPanel.setVisible(false);
    }//GEN-LAST:event_btnLaporanInputMouseClicked

    private void btnCekKtpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCekKtpMouseClicked
        // TODO add your handling code here:
        ktpCek.setVisible(true);
        homePanel.setVisible(false);
        laporanInput.setVisible(false);
        ktpInput.setVisible(false);
        laporanCek.setVisible(false);
        defaultPanel.setVisible(false);
    }//GEN-LAST:event_btnCekKtpMouseClicked

    private void btnCekLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCekLaporanMouseClicked
        // TODO add your handling code here:
        laporanCek.setVisible(true);
        homePanel.setVisible(false);
        laporanInput.setVisible(false);
        ktpCek.setVisible(false);
        ktpInput.setVisible(false);
        defaultPanel.setVisible(false);
    }//GEN-LAST:event_btnCekLaporanMouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Login main = new Login();
        main.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void pekerjaanFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pekerjaanFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pekerjaanFieldActionPerformed

    private void statustFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statustFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statustFieldActionPerformed

    private void kirimButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimButtonActionPerformed
        // TODO add your handling code here:
        String nik = nikField.getText();
        String nama = namaField.getText();
        String alamat = alamatTextArea.getText();
        String rt_rw = rtField.getText();
        String desa = desatField.getText();
        String kecamatan = kecField.getText();
        String kabupaten = kabField.getText();
        String warga = wargaField.getText();
        String ttl = ttlField.getText();
        String pekerjaan = pekerjaanField.getText();
        String status = statustField.getText();
        String laki = lakiButton.getText();
        String perempuan = perempuanButton.getText();
        String noTelp = noTelpField.getText();
        String statusValidasiKtp = "";
    

                if (nik.equals("") || nama.equals("") || rt_rw.equals("") || 
                        alamat.equals("") || desa.equals("") || kecamatan.equals("")
                        || kabupaten.equals("") || warga.equals("") || ttl.equals("")
                        || pekerjaan.equals("") || status.equals("") || noTelp.equals("")) {
                JOptionPane.showMessageDialog(null, "Tolong Input Data Secara Lengkap!", "Gagal!", JOptionPane.INFORMATION_MESSAGE);
                 } else {
                    
                    try {
                String kelamin = "";
                if (lakiButton.isSelected()) {
                    kelamin += laki;
                } else if (perempuanButton.isSelected()) {
                    kelamin += perempuan;
                }     
                
                Class.forName("com.mysql.cj.jdbc.Driver");
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/simpeda", "root", "sinheul24");
                java.sql.Statement stmt = con.createStatement();
                
                 // Inserting data in database
                String q1 = "insert into pengajuan_ktp values('" + nik + "', '" + nama + "', '" + alamat + "',  '" + rt_rw + "', '" + desa + "', '" 
                        + kecamatan + "','" + kabupaten + "', '" + warga + "', '" + ttl + "', '" + pekerjaan + "', '" + status + "'"
                        + ", '" + kelamin + "', '" + noTelp + "', '" + statusValidasiKtp + "')";
                int x;
                x = stmt.executeUpdate(q1);
                if (x > 0)
                    JOptionPane.showMessageDialog(null, "Data Tersimpan!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan!", "Gagal", JOptionPane.INFORMATION_MESSAGE);
                con.close();
            } catch (HeadlessException | ClassNotFoundException | SQLException exception) {
                System.out.println(exception);
            }
        }
    }//GEN-LAST:event_kirimButtonActionPerformed

    private void kejahatanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kejahatanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kejahatanRadioButtonActionPerformed

    private void pelecehanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pelecehanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pelecehanRadioButtonActionPerformed

    private void lainnyaLapFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lainnyaLapFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lainnyaLapFieldActionPerformed

    private void kirimLapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kirimLapButtonActionPerformed
        // TODO add your handling code here:
        String nik = nikLapField.getText();
        String nama = namaLapField.getText();
        String rt = rtLapField.getText();
        String rw = rwLapField.getText();
        String no = noTelpLapField.getText();
        String tgl = tglLapField.getText();
        String isiLaporan = isiLapTextArea.getText();
        String lakiLaki = lakiLapButton.getText();
        String perempuan = perempuanLapButton.getText();
        String pelecehan = pelecehanRadioButton.getText();
        String kejahatan = kejahatanRadioButton.getText();
        String jalanRusak = jalanRusakRadioButton.getText();
        String kategoriLainnya = lainnyaLapField.getText();
        String statusValidasiLaporan = "";

        if (nik.equals("") || nama.equals("") || rt.equals("") || rw.equals("") || no.equals("") || tgl.equals("")|| isiLaporan.equals("")) {
            JOptionPane.showMessageDialog(null, "Tolong Input Data Secara Lengkap!", "Gagal!", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                String kelamin = "";
                if (lakiLapButton.isSelected()) {
                    kelamin += lakiLaki;
                } else if (perempuanLapButton.isSelected()) {
                    kelamin += perempuan;
                }

                String kategoriLaporan = "";
                if (pelecehanRadioButton.isSelected()) {
                    kategoriLaporan += pelecehan;
                } else if (kejahatanRadioButton.isSelected()) {
                    kategoriLaporan += kejahatan;
                } else if (jalanRusakRadioButton.isSelected()) {
                    kategoriLaporan += jalanRusak;
                } else if (lainnyaRadioButton.isSelected()) {
                    kategoriLaporan += kategoriLainnya;
                }

                Class.forName("com.mysql.cj.jdbc.Driver");
                java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/simpeda", "root", "sinheul24");
                java.sql.Statement stmt = con.createStatement();

                // Inserting data in database
                String q1 = "insert into pengajuan_laporan values('" + nik + "', '" + nama + "', '" + rt + "',  '" + rw + "', '" + kelamin + "', '" + no + "','" + kategoriLaporan + "', '" + tgl + "', '" + isiLaporan + "', '" + statusValidasiLaporan + "')";
                int x;
                x = stmt.executeUpdate(q1);
                if (x > 0)
                    JOptionPane.showMessageDialog(null, "Data Tersimpan!", "Berhasil", JOptionPane.INFORMATION_MESSAGE);
                else
                    JOptionPane.showMessageDialog(null, "Data Tidak Tersimpan!", "Gagal", JOptionPane.INFORMATION_MESSAGE);
                con.close();
            } catch (HeadlessException | ClassNotFoundException | SQLException exception) {
                System.out.println(exception);
            }
        }
    }//GEN-LAST:event_kirimLapButtonActionPerformed

    private void lainnyaRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lainnyaRadioButtonActionPerformed
        // TODO add your handling code here:
        if (lainnyaRadioButton.isSelected()){
            lainnyaLapField.setEnabled(true);
            pelecehanRadioButton.setEnabled(false);
            jalanRusakRadioButton.setEnabled(false);
            kejahatanRadioButton.setEnabled(false);
        } else{
            lainnyaLapField.setEnabled(false);
            pelecehanRadioButton.setEnabled(true);
            jalanRusakRadioButton.setEnabled(true);
            kejahatanRadioButton.setEnabled(true);
        }
    }//GEN-LAST:event_lainnyaRadioButtonActionPerformed

    private void lakiLapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiLapButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiLapButtonActionPerformed

    private void tglLapFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglLapFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tglLapFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea alamatTextArea;
    private javax.swing.JLabel btnCekKtp;
    private javax.swing.JLabel btnCekLaporan;
    private javax.swing.JLabel btnHome;
    private javax.swing.JLabel btnInput;
    private javax.swing.JLabel btnKtpInput;
    private javax.swing.JLabel btnLaporanInput;
    private javax.swing.JPanel conten;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JTextField desatField;
    private javax.swing.JPanel homePanel;
    private javax.swing.JTextArea isiLapTextArea;
    private javax.swing.ButtonGroup jKelamin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JRadioButton jalanRusakRadioButton;
    private javax.swing.JTextField kabField;
    private javax.swing.JTextField kecField;
    private javax.swing.JRadioButton kejahatanRadioButton;
    private javax.swing.JButton kirimButton;
    private javax.swing.JButton kirimLapButton;
    private javax.swing.JPanel ktpCek;
    private javax.swing.JPanel ktpInput;
    private javax.swing.JTextField lainnyaLapField;
    private javax.swing.JRadioButton lainnyaRadioButton;
    private javax.swing.JRadioButton lakiButton;
    private javax.swing.JRadioButton lakiLapButton;
    private javax.swing.ButtonGroup lapButtonGroup;
    private javax.swing.JPanel laporanCek;
    private javax.swing.JPanel laporanInput;
    private javax.swing.JPanel logo;
    private javax.swing.JTextField namaField;
    private javax.swing.JTextField namaLapField;
    private javax.swing.JTextField nikField;
    private javax.swing.JTextField nikLapField;
    private javax.swing.JTextField noTelpField;
    private javax.swing.JTextField noTelpLapField;
    private javax.swing.JTextField pekerjaanField;
    private javax.swing.JRadioButton pelecehanRadioButton;
    private javax.swing.JRadioButton perempuanButton;
    private javax.swing.JRadioButton perempuanLapButton;
    private javax.swing.JTextField rtField;
    private javax.swing.JTextField rtLapField;
    private javax.swing.JTextField rwLapField;
    private javax.swing.JPanel side;
    private javax.swing.JTextField statustField;
    private javax.swing.JTextField tglLapField;
    private javax.swing.JTextField ttlField;
    private javax.swing.JTextField wargaField;
    // End of variables declaration//GEN-END:variables
}